[package]
name = "quinn-proto"
version = "0.2.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>", "Dirkjan Ochtman <dirkjan@ochtman.nl>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/djc/quinn"
description = "State machine for the QUIC transport protocol"
keywords = ["quic"]
categories = [ "network-programming", "asynchronous" ]
workspace = ".."
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[badges]
maintenance = { status = "experimental" }

[dependencies]
byteorder = "1.1"
bytes = "0.4.7"
err-derive = "0.1.5"
fnv = "1.0.6"
lazy_static = "1"
rand = "0.6"
ring = "0.14.1"
rustls = { version = "0.15", features = ["quic"] }
slab = "0.4"
# slog = "2.2"
slog = { version = "2.2", features = ["max_level_trace", "release_max_level_warn"] }
webpki = "0.19"

[dev-dependencies]
assert_matches = "1.1"
hex-literal = "0.1.1"
untrusted = "0.6.2"
rcgen = "0.2"
#slog = { version = "2.2", features = ["max_level_trace"] } # For debugging
